name: Android Build Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ./frw

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Write Local Properties to File
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > ${{ github.workspace }}/frw/local.properties

      - name: Ensure Google Services JSON Exists
        run: |
          if [ -n "${{ secrets.GOOGLE_SERVICES }}" ]; then
            printf '%s' '${{ secrets.GOOGLE_SERVICES }}' > ${{ github.workspace }}/frw/app/src/debug/google-services.json
          else
            echo "Warning: GOOGLE_SERVICES secret is empty or missing!"
          fi

      - name: Run Lint Checks
        run: cd ./frw && ./gradlew lint

      - name: Build APK (No Upload)
        run: cd ./frw && ./gradlew assembleDebug
